# Generated by Django 4.2.5 on 2023-09-23 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
