# Generated by Django 4.2.5 on 2023-09-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
