# Generated by Django 4.2.5 on 2023-10-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_alter_class_class_code"),
        ("accounts", "0005_profile_last_logout_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="class_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classes.class",
            ),
        ),
    ]
