# Generated by Django 4.2.5 on 2023-09-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
