# Generated by Django 4.2.5 on 2023-09-25 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_post_header_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
