# Generated by Django 4.2.5 on 2023-09-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_post_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="header_image",
        ),
        migrations.AddField(
            model_name="post",
            name="post_files",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
