# Generated by Django 4.2.5 on 2023-10-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_remove_post_header_image_post_post_files"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="post_files",
            new_name="post_files1",
        ),
        migrations.AddField(
            model_name="post",
            name="post_files2",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
