# Generated by Django 4.2.5 on 2023-10-03 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_alter_class_class_code"),
        ("home", "0010_rename_post_files_post_post_files1_post_post_files2"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="class_field",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
            ),
        ),
    ]
