# Generated by Django 4.2.5 on 2023-10-03 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_alter_class_class_code"),
        ("home", "0011_post_class_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="class_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
            ),
        ),
    ]
