# Generated by Django 4.2.5 on 2023-09-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_remove_lesson_class_field_remove_lesson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lesson_files",
            field=models.FileField(blank=True, null=True, upload_to="lesson_files/"),
        ),
    ]
