# Generated by Django 4.2.5 on 2023-09-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_lesson_lesson_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
