# Generated by Django 4.2.5 on 2023-09-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="max_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
