# Generated by Django 4.2.5 on 2023-09-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0005_lesson_max_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="max_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
