# Generated by Django 4.2.5 on 2023-09-29 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0007_exercise_max_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="max_score",
        ),
    ]
