# Generated by Django 4.2.5 on 2023-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0010_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
