# Generated by Django 4.2.5 on 2023-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0011_exercise_is_correct_delete_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="is_correct",
        ),
        migrations.AddField(
            model_name="progress",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
