# Generated by Django 4.2.5 on 2023-09-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0012_remove_exercise_is_correct_progress_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
