# Generated by Django 4.2.5 on 2023-09-30 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0015_exerciseset_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name="exerciseset",
            name="score",
        ),
        migrations.DeleteModel(
            name="Progress",
        ),
        migrations.AddField(
            model_name="studentscore",
            name="exercise_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lessons.exerciseset"
            ),
        ),
        migrations.AddField(
            model_name="studentscore",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
