# Generated by Django 4.2.5 on 2023-09-30 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0018_alter_exercise_student_answer"),
    ]

    operations = []
