# Generated by Django 4.2.5 on 2023-09-30 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_alter_class_class_code"),
        ("lessons", "0019_auto_20230930_2027"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lesson_class",
            field=models.ManyToManyField(
                related_name="lessons",
                to="classes.class",
            ),
        ),
    ]
